version: 0.0
os: linux
files:
  - source: /    # Deploy everything from the root folder
    destination: /home/ec2-user/app/    # Target location on EC2 instance
hooks:
  AfterInstall:
    - location: app/scripts/create_env.sh  # Run the script to fetch and create the .env
    - timeout: 180
