version: 0.0
os: linux
files:
  - source: /
    destination: /root/app/
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 180
      runas: root

  AfterInstall:
    - location: scripts/create_env.sh
      timeout: 180
      runas: root
